version: '3.3'
services:
  db:
    network_mode: bridge
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data
      - ./cmd/database/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  server:
    network_mode: bridge
    restart: always
    depends_on:
      - db
    build:
      dockerfile: build/package/docker/server/Dockerfile
      context: .
volumes:
  db:
    driver: local